name: 'terraform_state_artifact'
description: 'Downloads and uploads your Terraform statefile as an encrypted Github Artifact'
author: 'Sturla Bragason'
inputs:
  encryptionkey:
    description: 'Used as a key to encrypt and decrypt the statefile artifact'
    required: true
  statefile_location:
    description: 'Specify the location of your Terraform statefile.'
    required: false
    default: ''
  download_upload:
    description: 'Specify whether to download and decrypt or upload and encrypt.'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - id: terraform_state_artifact_download
      if: ${{ github.event.inputs.download_upload == 'download' }}
      run: |
        $ArtifactName = "${{ github.ref_name }}" + "${{ inputs.statefile_location }}"
        $Repo = "${{ github.repository }}"
        $BaseUri = "https://api.github.com"
        $ArtifactUri = "$BaseUri/repos/$Repo/actions/artifacts"
        $Token = "${{ github.token }}" | ConvertTo-SecureString -AsPlainText
        $RestResponse = Invoke-RestMethod -Authentication Bearer -Uri $ArtifactUri -Token $Token | Select-Object -ExpandProperty artifacts
        if ($RestResponse){
          $MostRecentArtifactURI = $RestResponse | Sort-Object -Property created_at -Descending | where name -eq $ArtifactName | Select-Object -First 1 | Select-Object -ExpandProperty archive_download_url
          Write-Host "Most recent artifact URI = $MostRecentArtifactURI"
          if ($MostRecentArtifactURI){
            Invoke-RestMethod -uri $MostRecentArtifactURI -Token $Token -Authentication bearer -outfile ./state.zip
            Expand-Archive ./state.zip
            openssl enc -d -in ./state/terraform.tfstate.enc -aes-256-cbc -pbkdf2 -pass pass:"${{ inputs.encryptionkey }}" -out ."${{ inputs.statefile_location }}"/terraform.tfstate
          }
        }
      shell: pwsh
    - id: terraform_state_artifact_upload
      if: ${{ github.event.inputs.download_upload == 'upload' }}
      run: |
        $ArtifactName = "${{ github.ref_name }}" + "${{ inputs.statefile_location }}"
        $StateExists = Test-Path -Path ."${{ inputs.statefile_location }}"/terraform.tfstate -PathType Leaf
        if ($StateExists){
          openssl enc -in ."${{ inputs.statefile_location }}"/terraform.tfstate -aes-256-cbc -pbkdf2 -pass pass:"${{ inputs.encryptionkey }}" -out ."${{ inputs.statefile_location }}"/terraform.tfstate.enc
        }
      shell: pwsh
    - uses: actions/upload-artifact@v2
      with:
        name: terraformstatefile
        path: ."${{ inputs.statefile_location }}"/terraform.tfstate.enc
branding:
  icon: 'cloud'
  color: 'gray-dark'