name: Terraform State Artifact
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '11 11 11 * *'


jobs:
  terraform_download_job:
    runs-on: ubuntu-latest
    name: Downloading terraform_state_artifact
    steps:
      - id: terrafrom_artifact_download
        uses: sturlabragason/terraform_state_artifact@v2
        with:
          encryptionkey: ${{ secrets.pat }}
          download_upload: download
  terraform_upload_job:
    runs-on: ubuntu-latest
    name: Uploading terraform_state_artifact
    steps:
      - id: terrafrom_artifact_upload
        uses: sturlabragason/terraform_state_artifact@v2
        with:
          encryptionkey: ${{ secrets.pat }}
          download_upload: upload